### ISSUE TITLE
Question: Updating Logseq-Git-Sync-101

### ISSUE THREAD

**Issue by mruderman** [CharlesChiuGit/Logseq-Git-Sync-101#10]
Hi, given that I'm not very technical, are there any known problems with updating the scripts in this project for a logseq-git sync that's already setup and working (with older version of project)?

**Comment by CharlesChiuGit** [comment]
If the older is working fine, then it's not necessary to update the script. The new script is just more adaptable to multiple platforms and preventing possible failure.

**Comment by mruderman** [comment]
I have not had any overt data loss, but I worry sometimes if there is 'occult' loss, or issues with metadata that I'm not seeing. But from your reply, sounds like the risk of updating is likely not worth it. And thanks for your reply, and sharing this project more generally!

**Comment by CharlesChiuGit** [comment]
Actually I think it's safe to update the script, just make sure your graph it saved before you update anything.
Closing the issue, feel free to reopen it.
