### ISSUE TITLE
Unable to link working copy to folder on iPhone - “Name already in use. Choose any other name”

### ISSUE THREAD

**Issue by willcray** [CharlesChiuGit/Logseq-Git-Sync-101#14]
Hey, first of all, this is an awesome repo. This is a huge game changer for me and my Logseq experience. I appreciate you putting this together. I don’t have an issue with your repo, but I would appreciate any help you’re willing to offer with a small sync issue I’m having. 

I’m running in to a small issue where my phone has gotten out of sync following a phone upgrade. I’m unable to get working copy to recognize and track changes made via logseq on my phone. I don’t think working copy is properly linked to the local repo on my phone.

When I long-press the repo in working copy, hit “Share”, and then hit “Link Repository to Folder”, I get an error message that says “Filename already in use. Pick some other name.”

In order to fix this, I’ve picked some other folder, then tried the same process to link it to the folder of interest. I receive the same error. I’ve also tried deleting the repository and re-cloning. I’ve also tried deleting working copy from my phone and following the whole setup procedure again.

I still cannot get local changes in logseq to be tracked in working copy, and therefore, I cannot get what I write in my phone to sync with the remote repository and other devices.

**Comment by CharlesChiuGit** [comment]
hmmm, interesting

**Comment by CharlesChiuGit** [comment]
Sorry, click the wrong button!

**Comment by CharlesChiuGit** [comment]
> When I long-press the repo in working copy, hit “Share”, and then hit “Link Repository to Folder”, I get an error message that says “Filename already in use. Pick some other name.”

This is expected, since u can only link one repo to one local folder at a time.

Have u tried create a new folder while chossing folder when doing `Link repo to Folder`?

**Comment by CharlesChiuGit** [comment]
@willcray did it fixed?

**Comment by CharlesChiuGit** [comment]
Close it as there's no further response, feel free to reopen it. 🙂
