### ISSUE TITLE
Question  re Version Control

### ISSUE THREAD

**Issue by thorrrr** [CharlesChiuGit/Logseq-Git-Sync-101#21]
Hi 
I followed you guide which is great and connection with pull and commit work fine.
But soon as i turn on version control in Logseq i get errors.

I am a very new to Github and Linux so if you knwp why please could you explain what the issue is?

![image](https://user-images.githubusercontent.com/8170673/208963377-a268f264-b584-4ecf-b1e4-c36bd91a0f98.png)

**Comment by CharlesChiuGit** [comment]
What's your OS? 
So u have place the ssh-key correctly, and it works fine without logseq's builtin version control, but as soon as u turn version control on, the error starts to pop?

**Comment by thorrrr** [comment]
i have just tried it 


![image](https://user-images.githubusercontent.com/8170673/208999398-6916a9ce-87a3-416b-8071-5235ed452d3d.png)

**Comment by thorrrr** [comment]
My SSH in Github


![image](https://user-images.githubusercontent.com/8170673/208999571-13fa04e9-fcf6-4dfa-b192-699bcf73c49e.png)

**Comment by thorrrr** [comment]
Was the shortcut 

Create git commit with message | ctrl+g c you wanted me to try?
If so this is what i used

**Comment by CharlesChiuGit** [comment]
Ys, it is.
So manual commit works and it triggers the post-commit hock, but auto-commit will have that ssh-key error?

**Comment by thorrrr** [comment]
Correct

**Comment by CharlesChiuGit** [comment]
Can u do `sudo dnf install ssh-askpass`? It looks like the package is missing.

**Comment by thorrrr** [comment]
> 

I have already tried that earlier today and then it asks for  GNOMES SSH error

![Screenshot from 2022-12-21 18-33-25](https://user-images.githubusercontent.com/8170673/209004597-83a36c61-f9be-4d8a-a3dc-96e2ecb2a960.png)

Very strange your bug page i have added this already ealier today i notice things keep going missing!!

**Comment by CharlesChiuGit** [comment]
`dnf install gnome-ssh-askpass` then?

**Comment by thorrrr** [comment]
THese are the options i have already tried OpenSSH that resulted in asking for Gnome
But the only mention of Gnome is a seahorse one !!!


![image](https://user-images.githubusercontent.com/8170673/209005478-dd417dce-834f-4df4-95de-265f7fddcff6.png)

**Comment by CharlesChiuGit** [comment]
I saw [this post](https://unix.stackexchange.com/questions/83986/tell-ssh-to-use-a-graphical-prompt-for-key-passphrase), maybe try `sudo dnf install openssh-askpass`?

**Comment by thorrrr** [comment]
As i mentioned that was the first error i got from LS  so that is what i installed
THen after installing that is started with GNome error

![image](https://user-images.githubusercontent.com/8170673/209006578-8fb6f5c8-26ff-489a-9a63-7381886f215a.png)

**Comment by CharlesChiuGit** [comment]
Hmmm, sorry I couldn't be more helpful on this issue. I'm pretty much debugging with u along the way.
To be sure, the ssh-key you generated is placed in `~/.ssh` right? (the `id_rsa.pub` file)

**Comment by thorrrr** [comment]
![image](https://user-images.githubusercontent.com/8170673/209007626-f4380a8e-7827-49d6-825b-15f5160ff20e.png)

**Comment by thorrrr** [comment]
Are you sure your Flathub software allows ssh keys with passcodes ?

**Comment by CharlesChiuGit** [comment]
hmm, u are using flatpak... I not sure if flatpak will work with auth processes or not, since flakpak is running in a sandbox.
Due to the sandbox, I think it will have a more complicate process to auth something.
Can u tried other format, like AppImage?

**Comment by CharlesChiuGit** [comment]
https://github.com/flatpak/flatpak/issues/1438
it seems like flatpak does need to pass in some extra arguments to make ssh work

**Comment by thorrrr** [comment]
> [flatpak/flatpak#1438](https://github.com/flatpak/flatpak/issues/1438) it seems like flatpak does need to pass in some extra arguments to make ssh work

Flatpak are the most reliable secure packages for Fedora the AppImage will not install its is looking and searching my whole system??? DO you have a link for this AppImage i been trying for 4 days to get this setup its a nightmare

**Comment by CharlesChiuGit** [comment]
https://github.com/logseq/logseq/releases/tag/0.8.14

**Comment by thorrrr** [comment]
Seriously 

![image](https://user-images.githubusercontent.com/8170673/209011662-8c68cd42-2acf-4e0f-9d9f-006f0a7ddab4.png)

**Comment by thorrrr** [comment]
Search finds nothing

**Comment by CharlesChiuGit** [comment]
How about ssh pass-in?
like `logseq --socket=ssh-auth`
have u tried this?

**Comment by thorrrr** [comment]
Where do you add this ?

Dale

**Comment by CharlesChiuGit** [comment]
Or tried ` Logseq-linux-x64-0.8.14.zip ` in the github release.
1. unzip it.
2. cd `Logseq-linux-x64`
3. try to run `./Logseq`, see if that works.
4. symlink the `Logseq` executable to your system bin, eg. `sudo ln -s /path/to/Logseq` /usr/bin`

**Comment by CharlesChiuGit** [comment]
> Where do you add this ? Dale

from the terminal?

**Comment by thorrrr** [comment]
> > Where do you add this ? Dale
> 
> from the terminal?

Are we talking about with the Flatpak image ?

**Comment by CharlesChiuGit** [comment]
https://opensource.com/article/21/5/launch-flatpaks-linux-terminal

**Comment by thorrrr** [comment]
Can you tell me how to correctly remove your AppImage  completely ?

**Comment by CharlesChiuGit** [comment]
just delete the Appimage itself would be fine.

**Comment by CharlesChiuGit** [comment]
did u solve the problem?

**Comment by thorrrr** [comment]
Yes as I mentioned I re did a SSH without passcode and this allows your Flatpak version to work. Not ideal but ok till you fix the issue

**Comment by CharlesChiuGit** [comment]
>  allows your Flatpak version

What do mean by **your** flatpak, I didn't publish any logseq flatpak. Also the logseq flatpak version is maintained [by community](https://github.com/flathub/com.logseq.Logseq/graphs/contributors/).

> Are you sure your Flathub software allows ssh keys with passcodes ?

I overlooked this line. It's on me, sorry.
But I also don't think you can use ssh-keys with passcode in logseq, there's no ui prompt in logseq for external programs.
You can submit a upstream PR to [logseq](https://github.com/logseq/logseq) to make it happened.

For a tech guy who value your security so much, maybe you should consider develop a plugin for that or hack your way out.

I don't think I can do much about it. I'll add a note for password-free ssh-keys is needed in this repo.

**Comment by thorrrr** [comment]
HI 
You have 2 tickets with this maybe you should merge to avoid duplication sede Issue #7815

**Comment by thorrrr** [comment]
> > allows your Flatpak version
> 
> What do mean by **your** flatpak, I didn't publish any logseq flatpak. The logseq flatpak version is maintained [by community](https://github.com/flathub/com.logseq.Logseq/graphs/contributors/).
> 
> > Are you sure your Flathub software allows ssh keys with passcodes ?
> 
> I overlooked this line. It's on me, sorry. But I also don't think you can use ssh-keys with passcode in logseq, there's no ui prompt in logseq for external programs. You can submit a upstream PR to [logseq](https://github.com/logseq/logseq) to make it happened.
> 
> For a tech guy who value he's own security so much, maybe you should consider develop a plugin for that or hack your way out.
> 
> I don't think I can do much about it. I'll add a note for password-free ssh-keys is needed in this repo.

I think if a user adds the ssh pvt to ssh-agent you app should pass it like all others do.
Your app should allow the best security possible IMHO

**Comment by CharlesChiuGit** [comment]
What ticket? Also are you talking in English?

**Comment by CharlesChiuGit** [comment]
Wait a second bro, I didn't create Logseq! I'm just a random guy!

**Comment by thorrrr** [comment]
HI

Sorry I thought you were replying as a Dev
Ignore comments then have a good festive season

**Comment by CharlesChiuGit** [comment]
Hope u have a gd one too!
