### ISSUE TITLE
Add the official Logseq sync option

### ISSUE THREAD

**Issue by janbaykara** [CharlesChiuGit/Logseq-Git-Sync-101#23]
It's now available for paid users, so I feel it'd be worth adding it + tips + issues to the diagram.

Tips probably still include working on one device at a time. Issues can include file overwriting.

**Comment by CharlesChiuGit** [comment]
Unfortunately, I not a active Logseq Sync user, so I can't really give advises about Logseq Sync.
Also, this repo is aim to "self-managed syncing system", so I'm not sure about adding Logseq sync to it, it seems misleading.

But if you have some good advise about Logseq Sync, PR is always welcomed! Or open a draft to see how we can sort thins out.

**Comment by CharlesChiuGit** [comment]
Closing the issue for no further response.
