### ISSUE TITLE
set up Git sync for existing graphs

### ISSUE THREAD

**Issue by jialori** [CharlesChiuGit/Logseq-Git-Sync-101#24]
It seems the current instructions only work if you initialize a new graph (as the step states in https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/For-Windows-users). How can I adapt these instructions on already existing graph(s)?

**Comment by CharlesChiuGit** [comment]
After you finished step 5, u can just move everything in the old graph to that new folder.

**Comment by CharlesChiuGit** [comment]
If you're not sure what your doing, always make a backup first.

**Comment by CharlesChiuGit** [comment]
Closing the issue for no further response.
