### ISSUE TITLE
Windows Instructions do not work GitHub does not trust PC without SSH ?????

### ISSUE THREAD

**Issue by thorrrr** [CharlesChiuGit/Logseq-Git-Sync-101#25]
Hi
I have tried following your [instructions ](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/For-Windows-users)but GitHub will not allow connection 
![image](https://user-images.githubusercontent.com/8170673/210350310-d020a431-7cf3-4f4e-8208-ec5eeb63deb8.png)

You say do not use SSH but github help says to avoid this error use ssh ?????

**Comment by CharlesChiuGit** [comment]
> `SSH-key without passward` is preferred

doesn't mean do not use ssh-keys

**Comment by thorrrr** [comment]
> > `SSH-key without passward` is preferred
> 
> doesn't mean do not use ssh-keys.
> 
> Please, use the ssh-key.

HI Charles 
But your Windows docs do not mention this!

**Comment by CharlesChiuGit** [comment]
It's in https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/%F0%9F%AA%9C-Workflow.
Please read all the guilds, thanks.

**Comment by thorrrr** [comment]
> It's in https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/%F0%9F%AA%9C-Workflow. Please read all the guilds if you're not familiar with git , thanks.

HI
Sorry i didnt see that i have SSH from my Linux laptop for same repo can i use that if i copy the key into my windows machine or should i make a new ssh key ?

**Comment by CharlesChiuGit** [comment]
Every machine should has their own ssh-key, please make a new one for your windows machine.

**Comment by thorrrr** [comment]
> Every machine should has their own ssh-key, please make a new one for your windows machine.

OK thank you so one i have set up a new ssh doi i just follow the windows instructions as i have a repiosirtry already i just need to pull from github as i have no loqseq files on my Windows yet?

**Comment by CharlesChiuGit** [comment]
Yes exactly!

**Comment by CharlesChiuGit** [comment]
Do remember to update the git-hooks.

**Comment by thorrrr** [comment]
> Do remember to update the git-hooks.

I have added a SSH key into Github from this PC and when i try again with Git now it says it does not exsist ???

$ git clone git@github.com:{thorrrr}/{logseq}.git
Cloning into '{logseq}'...
fatal: remote error:
is not a valid repository name

In Linux this worked flawlesley

**Comment by CharlesChiuGit** [comment]
Did you literally type `{}` in the command line?

**Comment by thorrrr** [comment]
Sorry fixed and working now 
Thank You for your patience

**Comment by thorrrr** [comment]
HI Charles
NOt sure if i screwed up yesterday but everything came through to my WIndows machine.
But i now get errors on my laptop 
From github.com:thorrrr/logseq
ceccf99..e8a4c20 main -> origin/main
Updating ceccf99..e8a4c20
Fast-forward
pages/Contents.md-3 | 0
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 pages/Contents.md-3
fatal: cannot lock ref 'HEAD': is at e8a4c20b64a7040591510065bcaed23d55cc5f82 but expected ceccf99ffac298cf15a623ac49ef19060a6e7d75

If you don't want to see those errors or don't need git, you can disable the "Git auto commit" feature on Settings > Version control.

Also on my iPad i can see the pages but they no longer commit what the pull from Github
Could you point me how to fix it please no doubt i have made an error

**Comment by thorrrr** [comment]
I have done a git status and pull and it looks to have grabbed them but i thought this method was automatic

![image](https://user-images.githubusercontent.com/8170673/210548812-ac6d679c-211b-461a-8211-a5dc09a03461.png)

**Comment by CharlesChiuGit** [comment]
As u can you have a git conflict on your windows machine, so nothing can be push or pull at this moment, not until u fix the conflict. 

The best approach for u now is to move what's not being pushed, re-do setup on your windows machine, add new notes back and try to push again.

This git sync method is indeed automatic, but now u have a git conflict, so it has been blocked until u solve it.

**Comment by CharlesChiuGit** [comment]
1. I never heard of "git irc", wtf is it?
2. Despite git in logseq is stupid, u need it.
3. I have a hard time understanding your English.
4. So did u do what I said in the previous comment?

**Comment by thorrrr** [comment]
I am re doing everything from scratch as you mentioned but i do not understand No 7 
Copy&paste the post-commit and pre-commit in .git/hooks. (Note: this folder could be hidden)


![image](https://user-images.githubusercontent.com/8170673/210565582-427d27a1-2149-47e2-aa9a-23dc2fe18894.png)

![image](https://user-images.githubusercontent.com/8170673/210565745-96d298c4-8eff-4b3a-8502-f678d9b3cc63.png)

GIT IRC

![image](https://user-images.githubusercontent.com/8170673/210565853-4e149155-9d88-48a7-b1f9-32000dc42d95.png)

**Comment by CharlesChiuGit** [comment]
If you don't want to deal with git, you can always choose to paid for Logseq Sync. Here's [the link](https://blog.logseq.com/how-to-setup-and-use-logseq-sync/).

**Comment by thorrrr** [comment]
HI Charles
Thank you i decided to fllow your advice plus support the Loqseq Team.
Could you tell me how to stop Git from syncing on my laptop and Pc do i disable options in Github or on my machines.
I would use Logseq Sync to Syync 
I was thinking of just using Git as a backup to Github if possible 
Could you advice or point me to docs to find out how to do this ?

**Comment by CharlesChiuGit** [comment]
> Could you tell me how to stop Git from syncing on my laptop and Pc do i disable options in Github or on my machines.

Just remove the `.git` folder and you'll be good! 👍

**Comment by thorrrr** [comment]
You mean the one on each machine  the .git
![image](https://user-images.githubusercontent.com/8170673/211806354-d6a0936a-6d8d-4e0c-b2f8-c1980d569f56.png)

**Comment by CharlesChiuGit** [comment]
ys, the `.git` folder in your Logseq graph.

**Comment by thorrrr** [comment]
Hi Charles 
I have deleted it but when i open Logseq i get an errror .git missing and a new .git file bac in folder ??

![image](https://user-images.githubusercontent.com/8170673/211808743-b1dbba0d-e26f-4016-b5a0-4c86db37192a.png)
The new .git file is created each time with this code in it 
```gitdir: /home/dale/.logseq/git/_home_dale_Loggy/.git```

**Comment by CharlesChiuGit** [comment]
Okey, then delete that `.git` file and `.gitignore` and toggle off the `Enable Git auto commit` option in Logseq settings.
![圖片](https://user-images.githubusercontent.com/32497323/211809638-a143dbfc-fe6d-4655-82d1-124d31f62000.png)

**Comment by thorrrr** [comment]
Cheers worked a treat
