### ISSUE TITLE
github unreachable on android.

### ISSUE THREAD

**Issue by zephyrs311** [CharlesChiuGit/Logseq-Git-Sync-101#28]
thank u for provide these methods。
I have a problem。
I have already done the first 6 steps。
I have configured the key。（.ssh）
but when i git clone。
it still needs me to input password

**Comment by CharlesChiuGit** [comment]
Hi, can u tell what this command's result?
`ssh -T git@github.com`

This command shows if your ssh-key is properly added to your github account.

**Comment by CharlesChiuGit** [comment]
> shows“[git@github.com](mailto:git@github.com)‘s password：”

In this case, I think your ssh-key is not added correctly. I would recommend redo the previous step again.

**Comment by zephyrs311** [comment]
> > shows“[git@github.com](mailto:git@github.com)‘s password：”
> 
> In this case, I think your ssh-key is not added correctly. I would recommend u to redo the previous steps again.
but when i command
$ ssh -T -p 443 git@ssh.github.com
Hi zephyrs311! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by CharlesChiuGit** [comment]
> Hi zephyrs311! You've successfully authenticated, but GitHub does not provide shell access.

Hmmm, interesting. So the ssh-key is added correctly but u need to specify the port.
Where do u find this solution?

**Comment by CharlesChiuGit** [comment]
Also in this case, maybe u can `git clone` now?

**Comment by zephyrs311** [comment]
i still can't git clone
i am chinese,i serch the problem in a China Programming Forum（CSDN）.
It needs me to"Add the following contents to the config file according to the document prompts. If there is no config, create a new one (in your. ssh folder) and delete the suffix name."
but i don't how to command this on a phone
![image](https://user-images.githubusercontent.com/123920983/217120111-c38cb20c-98ac-46de-98cb-24ce763e6bcb.png)
CSDN website:
https://so.csdn.net/so/search?spm=1001.2101.3001.7499&q=github%20%E9%85%8D%E7%BD%AE%E4%BA%86%E5%85%AC%E9%92%A5%E4%BE%9D%E6%97%A7%E6%8F%90%E7%A4%BAgit%40github.com%26lsquo%3Bs%20password&t=&u=&utm_medium=distribute.pc_search_hot_word.none-task-hot_word-alirecmd-1-github%20%E9%85%8D%E7%BD%AE%E4%BA%86%E5%85%AC%E9%92%A5%E4%BE%9D%E6%97%A7%E6%8F%90%E7%A4%BAgit%40github.com&lsquo%3Bs%2520password-null-null.172%5Ev8%5Econtrol=undefined&depth_1-utm_source=distribute.pc_search_hot_word.none-task-hot_word-alirecmd-1-github%20%E9%85%8D%E7%BD%AE%E4%BA%86%E5%85%AC%E9%92%A5%E4%BE%9D%E6%97%A7%E6%8F%90%E7%A4%BAgit%40github.com

**Comment by zephyrs311** [comment]
ok thank u for your patience and guidance.
maybe i should learn VIM and set proxy.

**Comment by CharlesChiuGit** [comment]
No need to learn a lot of vim stuff, just the very basic of how to open the file, how to enter insert mode and how to save and exit.

**Comment by CharlesChiuGit** [comment]
Closed for no further response, feel free to reopen it.
