### ISSUE TITLE
fatal: cannot lock ref 'HEAD'

### ISSUE THREAD

**Issue by szjani** [CharlesChiuGit/Logseq-Git-Sync-101#29]
I get this weird message on Windows if and only if I modified the graph on my iPhone. Although this message box appears, everything looks fine, the modifications are visible. Still, very annoying. If I manually run fetch or pull from Git bash, there is no such issue.
![image](https://user-images.githubusercontent.com/545872/220484753-68334e3a-7663-4cf8-84f5-221fe780fdb8.png)

**Comment by CharlesChiuGit** [comment]
r u kept both windows logseq and ios logseq opened at the same time?

**Comment by szjani** [comment]
No, they are not opened at the same time. There is no conflict.

**Comment by CharlesChiuGit** [comment]
Sorry, this is beyond my pay grade. I'm not 100% sure how built-in git in logseq works.
Personally I never ran into this after I use [this plugin](https://github.com/haydenull/logseq-plugin-git) with manually git pull/push via it.
Maybe consider give it a try?

**Comment by szjani** [comment]
I've setup Logseq on a Linux device and have the same issue. The `~/.gitconfig` contains only the name and email address, nothing else.

**Comment by CharlesChiuGit** [comment]
So did u try the git plugin instead of built-in auto-commit?

**Comment by szjani** [comment]
No, not yet. I'm going to check that, but honestly I would not like to commit manually. And I think the issue happens during pull, in the pre-commit hook.

**Comment by CharlesChiuGit** [comment]
ys, I do know it's related to pull. Will be greatly appreciated if u have a better idea about pre-commit!

**Comment by szjani** [comment]
Could not find any meaningful thing. I cannot even find Google hits that anyone is doing git pull in pre-commit hook. It is strange that it is only a problem for me and I can reproduce it both on Windows 11 and on Ubuntu.

Anyway, I've installed the git plugin, it works as expected. I'm sure it will happen that I cannot find something on my phone because I forgot to commit/push on desktop. :(

**Comment by CharlesChiuGit** [comment]
Sorry, this is the best solution I can provide so far. PR is always welcomed.
Or maybe u can try the official logseq sync, which is pretty solid in my limited experience.
Close this issue for now, feel free to reopen it in the future.
