### ISSUE TITLE
Wrong path of source file on Android 11, and extra line needed for not asking for pass phrase.

### ISSUE THREAD

**Issue by SkyLull** [CharlesChiuGit/Logseq-Git-Sync-101#30]
Android version: 11
Phone brand: Sharp

My Termux install things under `~/../usr/bin` instead of `~/bin/`
So instead of `source ~/bin/source-ssh-agent`, I'll need to use `source ~/../usr/bin/source-ssh-agent/` for the ssh-agent to work.
But I'm not a professional android dev, not sure if this is a general case for android 11, or it only happens on my brand.

Also, I'll need to add `eval $(ssh-agent)` before source command so that the script won't ask me to enter pass phrase.

In sum, my pull-graph file now looks like this:
```bash
#!/usr/bin/bash
eval $(ssh-agent)  # extra line
source ~/../usr/bin/source-ssh-agent/ # path modified
cd {your repo location} 
git pull
```

**Comment by CharlesChiuGit** [comment]
https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/For-Android-users
Updated. Many tks!
