### ISSUE TITLE
How can apply the step 8 of guide for mac in case of linux?

### ISSUE THREAD

**Issue by callmehanu** [CharlesChiuGit/Logseq-Git-Sync-101#31]
I followed the MacOS guide for Linux case but the step 8 show me that message in the terminal

![image](https://user-images.githubusercontent.com/13230502/230509709-4f8adaa1-a9b5-4914-b524-07993162c03a.png)

**Comment by CharlesChiuGit** [comment]
remove "`" and "`"

**Comment by CharlesChiuGit** [comment]
Aha, u forgot to `cd` into the the `.git/hooks` folder. It's a hidden folder, use `ls -al` and you'll see it.

**Comment by CharlesChiuGit** [comment]
u need to place the `pre-commit` & `post-commit` in this folder lol.
It's in [here](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/tree/main/git-hooks).
Read the wiki carefully lol 🤣

**Comment by CharlesChiuGit** [comment]
hmmm, that's weird. never seen that before.
Could u tried disable all plugins and do a re-index in logseq?

**Comment by CharlesChiuGit** [comment]
Also what's the theme? It looks cool!

**Comment by CharlesChiuGit** [comment]
> I just switched to Linux last month.

Welcome to the penguin family!  🐧🐧🐧

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit really thanks ... sorry for my clumsiness, I just switched to Linux last month. Anyway... I finished all steps and seems have problems to sync
> 
> ![image](https://user-images.githubusercontent.com/13230502/230538668-06c0174c-ec16-4962-a361-85eb5379d213.png)

Wait a sec! I saw one weird thing!
U link the `.git` folder as a graph folder! That's not possible!
Instead, u should create the folder structure like this:
```
/home/{username}/Workspace/Logseq_db/.git
```

And the `Logseq_db` is where u should link to logseq as a graph.

**Comment by CharlesChiuGit** [comment]
So u can use logseq with git now?

**Comment by CharlesChiuGit** [comment]
yeah, it's going to be a tough war lol.

feel free to open a discussion instead of an issue if u need more elaborate steps!
