### ISSUE TITLE
cannot support this directory type

### ISSUE THREAD

**Issue by pandasAtHome** [CharlesChiuGit/Logseq-Git-Sync-101#34]
I follow the [doc](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/wiki/For-Android-users)

open logseq and selected the directory, but it throw error:

![image](https://user-images.githubusercontent.com/30644744/236622652-23ebd2ce-8a6c-4b9a-a04c-3eab3173a8d7.png)

**Comment by CharlesChiuGit** [comment]
I don't have an android device, so i can assist u in a certain level.

It seems like your a super random path, does this folder actually exist on your device? Can u show me your file manager's screenshot?

**Comment by CharlesChiuGit** [comment]
Close as there's no further response.

**Comment by misketmuskat** [comment]
Reopen it please. Having the same issue on Android:


https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/assets/71901736/78d6b78c-2571-4640-ad46-5fdcd0e8a9c8

**Comment by CharlesChiuGit** [comment]
@misketmuskat what's your termux version?

a friend of mine helped me test it on android, he suggest ppl with similar issues trying to place the git repo under `~/storage/shared`. 
also, he's termux version is v0.9.19. (i'm not sure if it's the latest version)

**Comment by misketmuskat** [comment]
Yes, thank you, this solved the problem.
Didn't use Termux:Widget extension tho. Just set two aliases "pull" and "push" and directed to them to bash scripts.

Thank you, everything works as expected now.

**Comment by misketmuskat** [comment]
Also, found that it is possible to autosync the git repo without hassling with Termux:Widgets.
Here is the related guide for autosync:
https://gist.github.com/Makeshift/43c7ecb3f1c28a623ea4386552712114

**Comment by CharlesChiuGit** [comment]
> Also, found that it is possible to autosync the git repo without hassling with Termux:Widgets. Here is the related guide for autosync: [gist.github.com/Makeshift/43c7ecb3f1c28a623ea4386552712114](https://gist.github.com/Makeshift/43c7ecb3f1c28a623ea4386552712114)

This seems interesting! Will add it to the wiki, tks!
