### ISSUE TITLE
Step 4 in For iOS iPadOS users (Working Copy) --> out of date

### ISSUE THREAD

**Issue by lennon101** [CharlesChiuGit/Logseq-Git-Sync-101#37]
Step 4 explains: 
> 4. When download is done, long-press on the repo > Share > Link Repository to Folder > My iPhone/iPad (I would suggest don't choose iCloud) > Logseq-icon folder > create a new sub-folder under the Logseq-icon one (I would suggest don't name the folder with the same name as your repo.) > click Done

However it seems the option to `Link Repository to Folder` is missing for me (see screenshot). My guess is that Working Copy has changed this in an update. My question is, what should I be clicking on instead? 

**Recommendation:** update the documentation to reflect these changes 

![2023-11-16 08 57 34](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/assets/1709944/25ab8a0f-e19a-4ca2-877a-c78192061c23)

**Comment by CharlesChiuGit** [comment]
yeah, i also noticed this few days ago, but haven't got time to update the wiki.
I'll update the wiki ASAP.

**Comment by lennon101** [comment]
@CharlesChiuGit yeah no worries! I ended up finding where the setting is. The `Link Repository to Folder` is now access via:
- tap on the repository
- then tap on the repository name again 
- then you'll see a carrot at the top of the screen --> tap on that

**Comment by CharlesChiuGit** [comment]
wow, u took a different approach then i do!
i used a more geeky way, which is initialize a folder then change it's remote url.
i guess your way is much more easier for averages to adopt! tks!

**Comment by CharlesChiuGit** [comment]
fixed at https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/commit/5ce93079a66f780be732cd4474b0e64bf4b2e3c7

**Comment by lennon101** [comment]
very well documented! thank you for putting all this together! <3
