### ISSUE TITLE
pre-commit hook fails on Linux

### ISSUE THREAD

**Issue by neon-moon** [CharlesChiuGit/Logseq-Git-Sync-101#4]
Running on Ubuntu 20.04 I get the below error message every time logseq attempts to commit. The script runs fine with bash, but errors out every time it is included in the git process.

```
10:01:01.880 › [Git] .git/hooks/pre-commit: 11: [[: not found
Already up to date.
```

**Comment by CharlesChiuGit** [comment]
Did you use the exact git-hooks files I provided? 
[line 11](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/blob/23ed346b83aea16466c5eeae44b3c3373670ec66/git-hooks/pre-commit#L11) shouldn't execute anything at all.

**Comment by CharlesChiuGit** [comment]
Maybe the space character or the newline character are having issues on windows and linux.
I don't think it's a big problem. But if you very want to get rid of it, maybe you can re-type the `pre-commits`. Remember to use the `.sample` files in the `.git/hooks` as template because the file type is very unique.

**Comment by neon-moon** [comment]
Once I made the slight modifications below it began working. May be useful to note for any additional Linux users. I didn't dive too much farther into it, but I am assuming the sh interpreter does not include the double brackets as valid if syntax.

Thanks again for putting this all together, very excited to get this all integrated!

```
#!/bin/sh

output=$(git pull --no-rebase)

# Handle non error output as otherwise it gets shown with any exit code by logseq
if [ "$output" = "Already up to date." ]
then
   # no ouput
   exit 0
else
   # probably error print it to screen
   echo "else"
   # echo $output
fi

git add -A
```

**Comment by CharlesChiuGit** [comment]
Interesting!
If it's the interpreter that goes wrong, maybe you can try replace `#!/bin/bash` with `#!/bin/sh`

**Comment by romilly** [comment]
It's not the interpreter. It's a bug in your pre-commit script, which has [[ ]] instead of [ ].

I'll do a pr later.

**Comment by CharlesChiuGit** [comment]
@romilly thanks! So my pre-commit script will act differently on different platform? Is there a more robust way to do it?

**Comment by romilly** [comment]
I'm no expert, and I have no access to Windows or OS/X - Linux only I'm afraid.

Also I am now getting a (slightly different) error. I'll do a PR when it's working :)

**Comment by CharlesChiuGit** [comment]
Cool!

**Comment by romilly** [comment]
Doh! The code is fine, it's the difference between sh and bash on recent Linuxes.

With `#!/bin/bash` as the shebang, all works.

**Comment by romilly** [comment]
And thanks for an excellent guide!

**Comment by CharlesChiuGit** [comment]
Cool! So just the shebang? `[[ ]]` is actuacally fine? If that's the only problem I'll fix it right now.
