### ISSUE TITLE
Question about your working process

### ISSUE THREAD

**Issue by mendax1234** [CharlesChiuGit/Logseq-Git-Sync-101#5]
After reading your document about logseq sync . Can l summarize the whole process into pushing your local to a github repo (public or private ? l don't know, l prefer private but l don't know whether it is supported) and clone it on your iPhone (l use iPhone so l only talk about iPhone here) ? Is that right? Besides , it seems that the working copy needs the pro version to do it. That's not user friendly.

**Comment by CharlesChiuGit** [comment]
Private repo will be just fine, like I mentioned in the readme.
And yes, you need WorkingCopy Pro for it. I'm not sure what you mean by **user friendly**, but I did give you the reason why you should pay for it. 
Btw, If you're a student, I also mentioned that you can apply for github student pack for one year of free WorkingCopy Pro.

**Comment by mendax1234** [comment]
>I'm not sure what you mean by user friendly

l mean that someone may noy want to pay for it.

>Btw, If you're a student, I also mentioned that you can apply for github student pack for one year of free WorkingCopy Pro.

 How to do that? Is it in the Github student pack? Can you provide a link? 
Thanks.

--Daniel

**Comment by CharlesChiuGit** [comment]
1. I don't think that how user friendly normally means. There's not thing I can do if you don't want to pay for it.
2. It's mentioned in [the section](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101#-for-iosipados-users), please read it thoroughly. Or [github student pack](https://education.github.com/pack).

**Comment by mendax1234** [comment]
l can't find the page to log in on my iphone.

**Comment by CharlesChiuGit** [comment]
What do you mean...?
I have to sign up for it.
![image](https://user-images.githubusercontent.com/32497323/170697507-daf29bae-4b05-4433-96cc-97e3e4acf0cb.png)

**Comment by mendax1234** [comment]
Emmm, l am a student now and l already have the pack , but l don't know where to log in on my working copy on iOS

**Comment by CharlesChiuGit** [comment]
https://workingcopyapp.com/education/verify/

**Comment by mendax1234** [comment]
Thanks! l have successfully logged in. And l still have some little questions. Can l use it until l am not a student? Or , it only has one year time?

**Comment by CharlesChiuGit** [comment]
As long as you're a student, you can apply it again after it's expired.

**Comment by mendax1234** [comment]
Thanks , l am still a little confused about its using on Windows.
![image](https://user-images.githubusercontent.com/62934294/170700297-5850aab3-b6f6-4720-a9a3-36b756877cac.png)
If l already have a logseq library where my notes are stored, l should use enter the folder and type `git init` in cmd to create a git? After doing that , l should upload it on my github?

**Comment by CharlesChiuGit** [comment]
Why not just copy all the notes to the new folder you just cloned? And link the new folder as a new graph in logseq?
Please do some research about git first, I have provide some simple material in the readme.

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/170702128-eefacdfa-e9aa-408a-aee7-4b39b329f497.png)
l think l can't use `git init `in my original logseq graph.

**Comment by mendax1234** [comment]
How to define the .gitignore file?

**Comment by CharlesChiuGit** [comment]
You can just edit the file name of a random txt file.

**Comment by mendax1234** [comment]
Can logseq push the commit to the repo automatically?

**Comment by CharlesChiuGit** [comment]
That's why I provide the `pre-commit` and `post-commit` files.

**Comment by mendax1234** [comment]
Thanks! It seems that after l copy these files to my ./git , l still can't push automatically.

**Comment by CharlesChiuGit** [comment]
Make sure you follow **EVERY** steps I wrote in the workflow.
Many have successfully adopt this workflow without much trouble, I can't help you debug everything.
I can only answer specific questions.

**Comment by mendax1234** [comment]
l want to make sure that if l want to push the commits automatically, l should copy and paste the two files in your ./git-hooks to the hook folder in my ./git . In that way , l can achieve pushing automatically, is that right?

**Comment by CharlesChiuGit** [comment]
Ys, if you do everything right than you can push the commits automatically.

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/170723465-876e03eb-fddd-4b07-9883-1f61e022836b.png)
l have double checked and find nothing wrong with it. Can you help me see if my all my files in the hook folder are right?

**Comment by CharlesChiuGit** [comment]
ys, that's the folder you put `pre-commit` and `post-commit`.

**Comment by mendax1234** [comment]
Yes , l can push it successfully.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/62934294/170802306-89f01079-d088-46a4-b42b-263e1dae0ef1.png">

**Comment by mendax1234** [comment]
Besides , where is the cloned repo on my iphone, l just can't find it.

**Comment by mendax1234** [comment]
l think the problem exists now is that l can't push the commits automatically .

**Comment by CharlesChiuGit** [comment]
Change the `main` in [this line](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/blob/23ed346b83aea16466c5eeae44b3c3373670ec66/git-hooks/post-commit#L3) to `master`.

**Comment by mendax1234** [comment]
I have done this but l still can't push the commti automatically. Do l also need to close the logseq or the Github Desktop that l use?

**Comment by mendax1234** [comment]
It seems that it works now but l have to wait a long time for it to push the commits automatically to the github. For example , l need to wait about 20 minutes. That's not so good.

**Comment by CharlesChiuGit** [comment]
What's the interval you set in here or in `config.edn`?
![image](https://user-images.githubusercontent.com/32497323/170812675-c04cc32d-f5c2-4e74-9ccf-233395b891d5.png)

**Comment by mendax1234** [comment]
![Uploading image.png…]()

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/170812789-49641650-9fe7-4401-8a04-9bb4861ac51b.png)

**Comment by mendax1234** [comment]
l think the seconds of the git auto commit is too long , but l don't know which one fits me better since l find that once l close the logseq ,it won't commit automatically. So , l suggest adding a function that auto commit once closing the window of logseq.

**Comment by CharlesChiuGit** [comment]
You can submit a feature request to logseq team.

**Comment by mendax1234** [comment]
Sure l will!

**Comment by CharlesChiuGit** [comment]
And please close the issue if you got nothing to ask.
