### ISSUE TITLE
git errors behind corporate firewall

### ISSUE THREAD

**Issue by elkrause** [CharlesChiuGit/Logseq-Git-Sync-101#6]
Hi! Great collection here for Logseq sync via Git!

I setup my private Gitea instance on a webhosting server and for my Windows PC I use my work PC and a corporate firewall. Via our proxy I could make it work with VS Code, but not with the auto-commit feature of Logseq. I deactivated the TLS and both VS Code and Logseq show this warning, but it seems that Logseq Git is not commiting. 

Should I add something to the Git Hooks?

![image](https://user-images.githubusercontent.com/53222869/172152540-f1c8ec38-c2bb-4d6a-8be3-9361217cc147.jpeg)

**Comment by CharlesChiuGit** [comment]
Have you asked your company's IT or MIS? I think it would be easier to fix this problem with their help.

**Comment by elkrause** [comment]
Thanks! Auto Commit and Proxy is set. I will check on the Discord server. 

VS Code is working under this conditions, Logseq not.

I can't ask our corporate IT :)
